[package]
name = "ray-tracing-in-one-weekend"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "lib"
path = "src/lib/lib.rs"

[[bin]]
name = "raytracer"
path = "src/main.rs"

[dependencies]
